"""Image generation clients — Vertex AI Imagen and stub for testing."""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from google import genai

from .. import config
from ..retry import with_retry

logger = logging.getLogger(__name__)


class ImageGenerationStrategy(ABC):
    """Abstract base for image generation backends."""

    @abstractmethod
    def generate(self, prompt: str) -> bytes | None:
        """Generate an image from a text prompt.

        Returns PNG image bytes on success, or None on failure.
        Image generation failures must never raise — they are non-blocking.
        """


class ImagenClient(ImageGenerationStrategy):
    """Calls Vertex AI Imagen to generate images from text prompts."""

    def __init__(
        self,
        project: str,
        location: str | None = None,
        model: str | None = None,
    ) -> None:
        self._project = project
        self._location = location or config.IMAGE_GENERATION_LOCATION
        self._model = model or config.IMAGE_GENERATION_MODEL
        self._client: genai.Client | None = None

    def _get_client(self) -> genai.Client:
        if self._client is None:
            from google import genai
            from google.genai import types

            self._client = genai.Client(
                vertexai=True,
                project=self._project,
                location=self._location,
                http_options=types.HttpOptions(
                    retry_options=types.HttpRetryOptions(),
                ),
            )
        return self._client

    def generate(self, prompt: str) -> bytes | None:
        """Generate an image using the Google Gen AI SDK.

        Returns PNG image bytes on success, None on any failure.
        """
        try:
            from google.genai import types

            client = self._get_client()

            def _call() -> bytes:
                response = client.models.generate_images(
                    model=self._model,
                    prompt=prompt,
                    config=types.GenerateImagesConfig(
                        number_of_images=1,
                        aspect_ratio="16:9",
                        output_mime_type="image/png",
                        person_generation="ALLOW_ALL",
                    ),
                )
                if not response.generated_images:
                    logger.warning(
                        "Imagen returned 0 images (safety filter / content "
                        "policy?) for prompt: %s | model=%s",
                        prompt,
                        self._model,
                    )
                    return None
                image_bytes = response.generated_images[0].image.image_bytes
                if not image_bytes:
                    logger.warning(
                        "Imagen returned empty image bytes (content policy?) "
                        "for prompt: %s | model=%s",
                        prompt,
                        self._model,
                    )
                    return None
                logger.debug(
                    "Imagen returned %d bytes for prompt: %.80s",
                    len(image_bytes),
                    prompt,
                )
                return image_bytes

            return with_retry(_call)
        except Exception:
            logger.warning(
                "Imagen API error for prompt: %s | model=%s",
                prompt,
                self._model,
                exc_info=True,
            )
            return None


class StubImageClient(ImageGenerationStrategy):
    """Returns canned PNG image bytes for testing.

    Imagen always returns PNG; the pipeline converts to WebP before upload.
    """

    # Valid 1×1 red PNG generated by Pillow (69 bytes)
    STUB_PNG = (
        b"\x89\x50\x4e\x47\x0d\x0a\x1a\x0a\x00\x00\x00\x0d\x49\x48\x44\x52"
        b"\x00\x00\x00\x01\x00\x00\x00\x01\x08\x02\x00\x00\x00\x90\x77\x53"
        b"\xde\x00\x00\x00\x0c\x49\x44\x41\x54\x78\x9c\x63\xf8\xcf\xc0\x00"
        b"\x00\x03\x01\x01\x00\xc9\xfe\x92\xef\x00\x00\x00\x00\x49\x45\x4e"
        b"\x44\xae\x42\x60\x82"
    )

    def __init__(self, should_fail: bool = False) -> None:
        self._should_fail = should_fail
        self._calls: list[str] = []

    def generate(self, prompt: str) -> bytes | None:
        self._calls.append(prompt)
        if self._should_fail:
            return None
        return self.STUB_PNG
